name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.101']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore _Development/Solution.proj
      - name: Build
        run: dotnet msbuild _Development/Solution.proj /t:_Build /p:Configuration=Release
      - name: Test
        run: dotnet msbuild _Development/Solution.proj /t:_Test /p:Configuration=Release